### ISSUE TITLE
OneClick: Make a query string or easy way to subscribe

### ISSUE THREAD

**Issue by taylorb-microsoft** [mohitbagra/vsts-extensions#15]
I would like to include a direct link so that I can provide easy directions for team members to subscribe to oneclick items.

**Comment by mohitbagra** [comment]
You can copy the url for a rule group and share it with your team. In the one click settings page, click on a rule group to open the rule group page and notice that the url includes rule group id. Just share that url with your team and when they hit that url, they'll get directly to that rule group. And the rule group page will have a subscribe icon at the top, so they can subscribe to it from that page.

**Comment by taylorb-microsoft** [comment]
Yes, that's what I have done for now - but it would if it was just a link I could skip the need for a Wiki with directions.

**Comment by mohitbagra** [comment]
Do you mean a link to explain how does subscription work and how to subscribe to a rule group?
