### ISSUE TITLE
hide redirect from form

### ISSUE THREAD

**Issue by ZakMak9** [mohitbagra/vsts-extensions#17]
Hello Bagra,
great extension, easy to use.
but it's a little limited. Would be great if you could hide the button "Configure rules" like [this](https://www.dropbox.com/s/6n91s2ziajujoel/hide%20settings%20button.PNG?dl=0)?
You should make only project's administrators to edit rules on W.I.T.

Tank you, great job.

**Comment by mohitbagra** [comment]
I hear what you're saying. I have got the same feedback from multiple customers. But I havent been able to find any good set of APIs to check permissions (whether or not current user is a project or account admin). I am on constant lookout for this as some of my other extensions too can make use of it.
Its on my radar but I dont have an ETA yet.
