### ISSUE TITLE
Checklist in TFS 2018.2 Work Item Template

### ISSUE THREAD

**Issue by cytron201** [mohitbagra/vsts-extensions#20]
Hi! We're not seeing the checklist in the TFS Template it's configured for. The add-in is installed, and a Checklist has been created against a work item (not mandatory) in the TFS Web UI.

Looking at a Work Item Template from the default process configuration (or the current project), I see what looks like a placeholder within the weblayout xml:

        

But besides that, there is no other reference to the checklist add-in.

Hoping this is just a setting as we'd really like to use this and build our own such customisation in future.

**Comment by TFSRobert** [comment]
Hey cytron201,

you only need to write the following code to your wit xml. (_Extensions_)
_My example is for OneClick. You must change the correct Id´s and Descriptions._
```
<WebLayout ShowEmptyReadOnlyFields="true">
<!--**********************Work Item Extensions**********************
Extension:
	Name: witoneclickactions
	Id: mohitbagra.witoneclickactions

	Group contribution:
		Id: mohitbagra.witoneclickactions.work-item-oneclick-group-hub
		Description: Work item form one click group

Note: For more information on work item extensions use the following topic:
http://go.microsoft.com/fwlink/?LinkId=816513
-->
   <Extensions>
      <Extension Id="mohitbagra.witoneclickactions" />
   </Extensions>
<SystemControls>
```

Later at the xml input the following: (_GroupContribution_)
```
</SystemControls>
   <Page Label="xxx" LayoutMode="FirstColumnWide">
      <Section>
         <Group Label="Status">
         </Group>
         <Group Label="Classification">
         </Group>
         <GroupContribution Label="Work item form one click group" Id="mohitbagra.witoneclickactions.work-item-oneclick-group-hub" />
      </Section>
```

Best regards
Robert

**Comment by cytron201** [comment]
@TFSRobert Superb thank you; works like a charm!

**Comment by mohitbagra** [comment]
Thanks @TFSRobert  :)

**Comment by sheldonhull** [comment]
Can anyone share what the proper code is for TFS for checklist? I'm unaware of how to grab these extension names directly, so the example above doesn't provide enough for me to implement.
