### ISSUE TITLE
[Work item checklist] Cannot choose projects/processes using checklist

### ISSUE THREAD

**Issue by xkmarcink** [mohitbagra/vsts-extensions#30]
It should be possible to choose which projects/processes use checklists. Now its global for account which is not necessarily good.

**Comment by mohitbagra** [comment]
You can do that via your admin process layout page. You can choose which work item form extensions are visible under a specific process. 

https://docs.microsoft.com/en-us/vsts/organizations/settings/work/custom-controls-process?view=vsts

**Comment by mohitbagra** [comment]
You'll see something like this - 
![image](https://user-images.githubusercontent.com/3766956/42238967-85cd463c-7ed0-11e8-9fbe-1b3a924614ca.png)

There would be a "hide" action in the ellipsis menu in Checklist group (ellipsis menu shows up on mouse over)

**Comment by xkmarcink** [comment]
Oh, mea culpa. Thanks.
