### ISSUE TITLE
Could not install vsix in On-Premises TFS 2017

### ISSUE THREAD

**Issue by Siva150790** [mohitbagra/vsts-extensions#33]
I couldn't install the vsix package of OneClick in TFS 2017 on premises version. Only in VisualStudio online i could install. I get the following alert msg

The extension mush support installation Target
Microsoft.VisualStudio.Services
Microsoft.TeamFoundation.Server.Integration
Microsoft.TeamFoundation.Server

![image](https://user-images.githubusercontent.com/25603378/43121918-f3f07c98-8f3c-11e8-950b-203b2b45394e.png)

**Comment by mohitbagra** [comment]
OneClick extension only supports VSTS, not TFS.
