### ISSUE TITLE
How to Debug this application in Visual Studio 2017, I'm new to VSCode

### ISSUE THREAD

**Issue by Siva150790** [mohitbagra/vsts-extensions#35]
Hi Mohit,

Please let me know how to debug this application using Visual Studio 2015 or 2017. I tried to create a empty solution and add all the files but compilation fails.

Is there any way to make this code work in Visual Studio?

**Comment by mohitbagra** [comment]
A VSTS extension is a webapp hosted on VSTS. So you dont need an editor to debug it. You can debug by running webpack in dev mode and inspecting typescript sourcemaps in chrome debugger

**Comment by Siva150790** [comment]
Thanks Mohit,  I'm trying to implement a similar application in TFS on premises. The below Api is working in VSTS but not in TFS. 

Is there any workaround.

![image](https://user-images.githubusercontent.com/25603378/43759013-990e783e-9a3b-11e8-8cbb-1cc7fedd38ef.png)

**Comment by mohitbagra** [comment]
What error are you getting? And which TFS version are you using?

**Comment by Siva150790** [comment]
"Sequence contains no matching element"  I get this error message when using TFS 2017 but it works fine in online Visual Studio.

**Comment by mohitbagra** [comment]
Can you send me a screenshot from browser network tool? I want to see what request is made (the request url) and the full response coming from it.
It would probably be because project level fields api is not supported in TFS 2017. 
Can you check if this works -

WitClient.getClient().getFIelds()   // not passing any project id

**Comment by Siva150790** [comment]
sure, I will check and update you with screenshot.

**Comment by Siva150790** [comment]
Hi Mohit, 
TFS Version : 15.112.26307.0 (Tfs2017.Update1)

Here is the response which i get.

{"$id":"1","innerException":null,"message":"Sequence contains no matching element","typeName":"System.InvalidOperationException, mscorlib","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}

![image](https://user-images.githubusercontent.com/25603378/43785888-fbde5576-9a84-11e8-97d2-cdcf99458010.png)

**Comment by mohitbagra** [comment]
https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/wit/fields?view=tfs-2017

TFS 2017 doesnt support project scoped fields API. So you can only get collection scoped fields by calling -

WitClient.getClient().getFields()    // dont pass project id

**Comment by Siva150790** [comment]
Thanks for the clarification Mohit. It works
