### ISSUE TITLE
Get Allowed values of WorkItemField

### ISSUE THREAD

**Issue by SateeshaMoolya** [mohitbagra/vsts-extensions#38]
Hi Mohit,
      I am trying to implement a similar application for our organization. I want to retrieve allowed values of work-item-field using the api you used in oneclick action.
![image](https://user-images.githubusercontent.com/42334396/44015194-794f4a9e-9eed-11e8-8739-67e6ae578089.png)
![image](https://user-images.githubusercontent.com/42334396/44015203-7f56ba08-9eed-11e8-9bf6-bdf973945b0d.png)

But the appi is throwing error for could you please help me here?
![image](https://user-images.githubusercontent.com/42334396/44015311-f95d27c4-9eed-11e8-991d-b5d0271b00ae.png)

**Comment by mohitbagra** [comment]
Are you working on VSTS or TFS? If TFS, which version?

**Comment by SateeshaMoolya** [comment]
I am using TFS Version 15.112.26307.0

**Comment by mohitbagra** [comment]
This api is very recently added, so its not supported for the version of TFS you are using
