### ISSUE TITLE
[Checklist] Group List Items

### ISSUE THREAD

**Issue by geirkairam** [mohitbagra/vsts-extensions#40]
We realy like the checklist extensions and use it a lot. Our checklist ist long so we would like to group todos (f.e. specification / implementation / deployment) or at least hide todos that are done. Are there any plans to include a function like this or would you accept a pull request for this new feature?

**Comment by mohitbagra** [comment]
I am working on a big change in the repo, so I dont have capacity to work on this. Can you submit a Pull request?

**Comment by mohitbagra** [comment]
I pushed an update today that lets user adds custom labels (similar to work item tags) to each checklist item, and a filter bar to filter items based on their labels. This should work similar to "grouping" items.
I also added a user scoped setting to hide completed items
