### ISSUE TITLE
TFS On-Prem

### ISSUE THREAD

**Issue by kerwinc** [mohitbagra/vsts-extensions#41]
Hey man, are you going to make Bug Bash Manager Pro available for on-prem users?

**Comment by mohitbagra** [comment]
I test my extensions only on Azure Devops Service, not on-prem. I tend to use latest rest apis and framework provided by extensibility service, so some features may not work on on-prem, depending on its version.

You are welcome to fork this repo, and generate a vsix for your on-prem use and validate that it works for you.
