### ISSUE TITLE
On-prem support?

### ISSUE THREAD

**Issue by jessehouwing** [mohitbagra/vsts-extensions#46]
The extension is currently only enabled for Azure DevOps, is there a reason this can't be supported on TFS 2018? (apart from the extra test work on your end?)

**Comment by mohitbagra** [comment]
Which extension in particular are you talking about? This repo holds 6 :)
I tend to test my extensions against AzureDevops only and I try to use the latest apis/sdks wherever possible, so I cannot guarantee onprem support. But feel free to fork the repo and modify the extension manifest to support onprem and test it out against your version of TFS

**Comment by jessehouwing** [comment]
Work item quick actions.

**Comment by droopygit** [comment]
Hi, congratulations for your extensions. I would also like to use it in Azure DevOps Server 2019, specifically the extension "Controls Library". Is this planned?

**Comment by mohitbagra** [comment]
Like I said, I tend to use latest apis/sdk and test my extensions on Azure Devops only. But feel free to fork the code and test it in your onprem server and if it works, you can publish it as a local extension in your onprem setup

**Comment by droopygit** [comment]
OK, thx.
