### ISSUE TITLE
Naming Checklists

### ISSUE THREAD

**Issue by Noumit** [mohitbagra/vsts-extensions#47]
Can I have multiple checklists in a Work Item? If so, I would like to give them all a unique name. Let me know if this is possible or will it be a future release.

**Comment by mohitbagra** [comment]
I can see a way to group checklist items and show items grouped by their group name. I'll have to think more about it

**Comment by mohitbagra** [comment]
The easiest solution I can think of is to let users assign a Label (or a set of Labels) to a checklist item and providing a way to filter checklist items by labels. 
This way, you will still see checklist items in the same view as now but you would be able to filter those out by Labels. My question to you is, do you think each checklist item should have only 1 label or should it allow multiple labels be assigned to it?

**Comment by Noumit** [comment]
For my need, only 1 label should be enough. I am guessing that the shared list labels can only be changed by the administrator of the site and personal checklists' label can be updated/created by the individuals as needed.

**Comment by mohitbagra** [comment]
I pushed an update today that lets user adds custom labels (similar to work item tags) to each checklist item, and a filter bar to filter items based on their labels. This should work similar to "grouping" items.
