### ISSUE TITLE
Add the ability for pre-set checklists to be deleted/edited on the work item

### ISSUE THREAD

**Issue by jdasilva-huntswood** [mohitbagra/vsts-extensions#51]
Add the ability for pre-set checklists to be deleted/edited on the work item. It currently does not allow this.

**Comment by mohitbagra** [comment]
By pre-set checklist, do you mean the checklist defined on work item type level (from the admin page)? You can edit/delete those by going to the checklist admin hub

**Comment by jdasilva-huntswood** [comment]
Hi, Yes that is what I mean by pre-set checklist. I would like for the ability to edit and delete checklist items within a work item (not the admin page which will affect all checklists of that type). Thereby allowing the team to have a set of items pre-populated for work items but able to delete if not applicable or edit.

**Comment by mohitbagra** [comment]
You can still create checklist items on a per-workitem basis from the extension in work item form (in addition to default checklist items per work item type). I use work item type default checklist as a way to pre-populate checklist for workitems. Does that not work for your scenario? If no, then why?

**Comment by mohitbagra** [comment]
Or are you talking about a team-scoped default checklist for all (or a subset of) work item types?

**Comment by mohitbagra** [comment]
No response since last month. Closing it for now. Please re-open if needed
