### ISSUE TITLE
Dumb question: in the new AzureDevops layout how do i find the settings? 

### ISSUE THREAD

**Issue by Sporran89** [mohitbagra/vsts-extensions#52]
The layout of the settings has changed with the new AzureDevops layout, and I cannot find the settings for the extension.

**Comment by mohitbagra** [comment]
Which extension's settings? OneClick or Checklist?

**Comment by mohitbagra** [comment]
The checklist settings are available at -
https://dev.azure.com/<<Account name>>/<<Project name>>/_settings/mohitbagra.workitem-checklist.settings-hub

The OneClick settings are available at -
https://dev.azure.com/<<Account name>>/<<Project name>>/_settings/mohitbagra.witoneclickactions.settings-hub
