### ISSUE TITLE
Customization with Checklist possible ?

### ISSUE THREAD

**Issue by ishah09** [mohitbagra/vsts-extensions#54]
Thankful for great extension !

1. Is it possible to handle label type, add/update it

![image](https://user-images.githubusercontent.com/32862749/55331377-c950be00-54b0-11e9-8ac7-ada03c98aafc.png)

2. Can you enhance it, to add attachment in individual checklist

**Comment by mohitbagra** [comment]
1. The extension only supports pre-defined labels - In Progress, Blocked, N/A and Completed. You cannot add new labels. You can however update the label of each checklist item by clicking the "pencil" icon on each checklist item. 

2. Thats a great suggestion. I'll see what I can do

**Comment by ishah09** [comment]
1. I have been required with few more label status, If you can look in to it. It would be great help. 
2. Attachment has not priority, But if its there it would be great help. 

Once again thanks, I found this extension much useful.

**Comment by mohitbagra** [comment]
I'll see what I can do. I dont have any capacity this month, but I should get to it next month

**Comment by ishah09** [comment]
@mohitbagra 
Can you please increase String limit from 128 to 255 OR something as fas it's possible

It would be great if you can do the needful as soon as possible, We are using your extension for Bug Reporting purpose and internal management.

**Comment by ishah09** [comment]
@mohitbagra 

It would be great help, if you can bring popup acknowledgment before to Delete any checklist point, 

Ref Example:
-We do have list of 20+ points, Want to edit one of them. While clicking on Edit icon, by mistake if its get click on Delete icon, the point is gone.

As extension don't have Sync with TFS history or DB, its been complex for us to maintain it with our important points. 

Looking forward to hear back you.
Thank you so much in advance.

**Comment by mohitbagra** [comment]
I'll be pushing an update this weekend. I'll make sure to add the confirmation popup too in that update

**Comment by mohitbagra** [comment]
I have published an update today which lets users add labels (similar to work item tags) to each checklist item. You cannot do it while creating an item, you can only do it while editing an existing item. I also added a filter bar where you can filter items by their labels. This should give you what you need.

Also, deleting an item now shows a confirmation dialog

**Comment by ishah09** [comment]
Hey, 
Thank you so much for bringing these new features, 

But, Filter label functionality is not working. Can you please fix it? 

![image](https://user-images.githubusercontent.com/32862749/59435892-35826300-8e0c-11e9-86f1-3758bc5c9247.png)

**Comment by mohitbagra** [comment]
Do you have any items in this work item with any of these 2 labels? Can you clear the filter and toggle "Show labels" from the settings icon (right next to refresh icon)  - this will start showing labels below each checklist item.

**Comment by ishah09** [comment]
I have did this all. And yes, it contains work itéms for same.
