### ISSUE TITLE
Teamcity - VSTS - Bug Bash Pro

### ISSUE THREAD

**Issue by PTassou** [mohitbagra/vsts-extensions#55]
Hello,

Can I ask if we have a way to automatically, when a build fails in teamcity, create a new bug in "Bug Bash Pro" with the tests that fails?

Thanks a lot :D

Panagiotis Tassou, Junior Software Quality Assurance Engineer

**Comment by mohitbagra** [comment]
I dont think thats possible. Azure devops extensions have limited functionalities, one of them being no ability to listen to external events. 
However, you can create an actual bug in Azure devops when  a build fails.

**Comment by PTassou** [comment]
Thanks a lot mate for your quick answer. Keep up the great work.
