### ISSUE TITLE
Checklist: Add Completed Date/Time and who completed

### ISSUE THREAD

**Issue by sitwalkstand** [mohitbagra/vsts-extensions#59]
Would it be possible to add the completed date/time and who completed the checklist item and then display that beside the checklist text?

**Comment by mohitbagra** [comment]
I can add this information to the new checklist items that are created after I have published this update on the marketplace. All the checklist items created before this feature was published still wont have this data. Is that ok with you?

**Comment by sitwalkstand** [comment]
That would be great.  I look forward to checking that out.  I'll keep an eye on this repo and see when the changes are added.

Thanks!

**Comment by mohitbagra** [comment]
Published this  feature today. Now you can see this info in a hover tooltip on the checkbox of a completed checklist item
