### ISSUE TITLE
One Click not triggered from Backlog GUI

### ISSUE THREAD

**Issue by MarcvanLint** [mohitbagra/vsts-extensions#73]
The One Click functions are not triggered when a new item is created from the backlog menu (Azure DevOps). I use this option to set various fields when a work item is created (e.g. populating a definition of done as the acceptance criteria). The One Click options are triggered when Work Items are created from other places in the GUI.

Scenario:
- Select Backlogs (the backlog will open (list of PBI)
- Select from the middle of the screen "+ New Work Item".
- Enter a description for the newly created PBI.
- Select "Add to the Bottom"

A new PBI is created. But the 'default fields' which should be set with the One Click are not populated.

**Comment by mohitbagra** [comment]
This extension is a work item form extension, so it only works in a work item form view. The extension has no way of knowing if the work item was created from any other form like backlog or board.
