### ISSUE TITLE
Extension has vanished in one of our Azure DevOps projects

### ISSUE THREAD

**Issue by wpschaub** [mohitbagra/vsts-extensions#98]
After a Microsoft update of Azure DevOps, the click-once extension disappeared on all work item types in one of our Azure DevOps projects, while other Azure DevOps projects did not have any changes. Microsoft suggested that we remove and install the extension again - before we do that drastic and uninuitive step, I want to ask two things:  

1. Has anyone else experienced this strange behaviour? If yes, how did you solve the problem?
2. If we remove and install the extension again, what happens with all the click-once configurations? We have many Azure DevOps projects that use the extension and I do not want to affect our users.

**Comment by wpschaub** [comment]
This was caused by a Microsoft feature. Hotfix is deploying to all AzDO rings as we type. Workaround is to enable Repos and Pipelines in the AzDO project.

**Comment by danhellem** [comment]
@wpschaub to be clear, this was not caused by a feature. It was caused by a bug that did not get noticed until it was deployed in a later ring. As you noted though, a fix is going out now and should reach all accounts in a day or two.
